### ISSUE TITLE
Table of Contents for some books do not show

### ISSUE THREAD

**Issue by dmpfaeffle** [hyphen-reader/hyphen#37]
I loaded  One of Us: The Story of Anders Breivik and the Massacre in Norway, there is no table of contents showing.  Why is that?

**Comment by matt-curtis** [comment]
This is a known bug on my end that's been fixed, but hasn't been released yet (it's in the 2.0 update). However I can't be certain that's what this is. Could you [attach the ePubs](https://www.sendspace.com/) or email them (hyphenreader@gmail.com) so that I may test them?

**Comment by dmpfaeffle** [comment]
emailed the book to you.

**Comment by matt-curtis** [comment]
I misspelled the email - it's hyphenreader@gmail.com.

**Comment by dmpfaeffle** [comment]
resent

**Comment by matt-curtis** [comment]
Got it.

Confirmed that it's the bug I thought it was. It's fixed in the [2.0 update](https://cloud.githubusercontent.com/assets/1414704/12963406/eb1d2baa-d00f-11e5-9e1d-07006deb00a4.PNG). The 2.0 update should be out soon, hopefully by the end of this month. You can [follow Hyphen on twitter](https://twitter.com/hyphenreader) to be notified (there will also be a beta first, so you'll be able to nab that.)
