### ISSUE TITLE
Setting to adjust paragraph spacing

### ISSUE THREAD

**Issue by ijudy** [hyphen-reader/hyphen#40]
This would also adjust space between bars or asterisks or other dingbats (or whatever they are called (help me or here). Thanks.

**Comment by matt-curtis** [comment]
This feature already exists. And I assume you're referring to superscript characters? Or just special characters?

**Comment by ijudy** [comment]
Yes. I recently noticed that there are 2 paragraph settings. Thanks.

Here’s something else i’ ve been thinking about. I have done some programming in the past. When I think of my ereader, I don’t associate that with programming CSS. But I see that for me to change my FONT COLOR in the COLORS AND FORMATTING SECTION, I had to dig into the PUBLISHER STYLING section and turn off TEXT COLORS. I don’t think the average user should have to figure that out. It should be grayed out and if the user clicks on it and tries to change the font color, they should get a pop-up explaining why that is disabled (unless you want to streamline this even more).

Thanks.

**Comment by matt-curtis** [comment]
Unfortunately though, practically every setting Hyphen makes available for customization is a setting that the Publisher could have overwritten in their own CSS. Following your idea, nearly every setting would have to be greyed out. The current system is designed so that you can achieve a balance in how the ePub's content is presented. You can either entirely disable Hyphen's formatting, or disable the publisher's formatting entirely, or something between - it's up to the user.

I agree that the user shouldn't have to think of CSS when customizing... I think it helps though that most concepts/settings are typographic concepts, and nothing strictly limited to or requiring a knowledge of CSS. Maybe though it would be better to swap 'CSS' for the more common and accessible 'Styling' in the UI? It also helps that users who have used other ePub readers will be familiar with the concept of 'Publisher Styling' vs. 'Reader Styling'.

**Comment by ijudy** [comment]
I used Marvin and didn’t think about the publisher’s styling. Mostly I want it. This may change. But font size depends on my device and i’d like to change some set styles depending on if it’s day or night and room brightness.

Maybe you could just disable settings that aren’t allowed to change in the publisher’s styling? What confused me is that I could select a different color for font color, but the color of the font on my text couldn’t change! If the publisher chose black text, it shouldn’t let me put the “underline”on the white color circle.

Thanks!

Judy

**Comment by matt-curtis** [comment]
> Maybe you could just disable settings that aren’t allowed to change in the publisher’s styling? What confused me is that I could select a different color for font color, but the color of the font on my text couldn’t change! If the publisher chose black text, it shouldn’t let me put the “underline”on the white color circle.

I see what you're saying, and I'll keep it in mind for future versions.
