### ISSUE TITLE
In-page popups: footnotes, dictionary

### ISSUE THREAD

**Issue by matt-curtis** [hyphen-reader/hyphen#5]
- ePub 3 Footnotes support
- Dictionary, Wikipedia (?)

**Comment by gennaios** [comment]
I do very much like the popup dictionary on iPhone; not needing to move my thumb way up to the top left, like with the system dictionary, is soo nice. I think it is possible to get the data from the system dictionary and display it as one would like; that's a possibility. Custom dictionaries too maybe someway.

One other thing, I'm of the belief that only swipes and taps in the margins should page turn. Taping or swiping in the text area could cause accidental turns and might be better reserved for features like toggling the toolbar, text selection, single tap panel dictionaries like many eInk eReaders, or something else.

**Comment by gennaios** [comment]
Saw another issue concerning this. But since I replied here. I didn't initially notice it was the system dictionary in a pop-up, since some words could show up in multiple languages, for instance 'vie' (life) shows only English. Perhaps it could show definitions from all system dictionaries, or at least prefer the language of the ePub if that's possible.

The vertical space for open and add to vocabulary, maybe they can be only icons and moved to the bottom right for example; that could save some space, and anyone that uses the app long enough, or checks some help screen, might not need the text labels.
